packages:
  - apps/*

catalog:
  '@commander-js/extra-typings': 14.0.0
  '@inquirer/prompts': 8.4.3
  '@types/node': 24.1.0
  '@types/pg': 8.20.0
  better-auth: 1.6.11
  chalk: 5.6.2
  commander: 14.0.3
  drizzle-orm: 1.0.0-beta.22
  esbuild: 0.28.0
  eslint: 9.39.2
  ora: 9.4.0
  typescript: 5.9.3
  yaml: 2.9.0

allowBuilds:
  '@swc/core': true
  esbuild: true
  sharp: false
  unrs-resolver: true
